### ISSUE TITLE
Detekce současného použití filteru number_format a currency

### ISSUE THREAD

**Issue by vodictomas** [modul-is/coding-standard#15]
nově se udělala změna v currency filteru - převádí na `hezké` číslo - mezera mezi tisicema atd

ale rozbíjí to následující kód, který máme v některých aplikacích

```
{$payAmount|number:0,',',' '|currency}
```

protože je tam pak dvojí formátování čísla a ve finále to třeba z 2000 udělá 2

dokážeme tohle detekovat a vyhodit chybu?

**Comment by spulakk** [comment]
Dokážeme, ale CS jako takový kontroluje jen PHP soubory. Můžu to tam přidat mimo, stejně jako převádění mezer, ale není to moc elegantní a nedává mi to pro CS úplně smysl vzhledem k tomu že `|currency` je jen náš kód.

**Comment by kravcik** [comment]
Vyřešeno, nově bude tohle kompatibilní mezi sebou.
